"""esquema inicial

Revision ID: 03d7ee18ac9b
Revises:
Create Date: 2026-09-28 14:31:41.769745
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import invertio.persistence.types

revision: str = "03d7ee18ac9b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("mode", sa.String(length=10), nullable=False),
        sa.Column("ts", invertio.persistence.types.UTCDateTime(), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("ix_audit_mode_ts", ["mode", "ts"], unique=False)

    op.create_table(
        "equity_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("mode", sa.String(length=10), nullable=False),
        sa.Column("ts", invertio.persistence.types.UTCDateTime(), nullable=False),
        sa.Column("venue", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("equity", invertio.persistence.types.DecimalString(length=40), nullable=False),
        sa.Column("cash", invertio.persistence.types.DecimalString(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("equity_snapshots", schema=None) as batch_op:
        batch_op.create_index("ix_equity_mode_venue_ts", ["mode", "venue", "ts"], unique=False)

    op.create_table(
        "signals",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("mode", sa.String(length=10), nullable=False),
        sa.Column("ts", invertio.persistence.types.UTCDateTime(), nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("venue", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=10), nullable=False),
        sa.Column("price", sa.Double(), nullable=False),
        sa.Column("stop_loss", sa.Double(), nullable=True),
        sa.Column("take_profit", sa.Double(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.create_index("ix_signals_mode_ts", ["mode", "ts"], unique=False)

    op.create_table(
        "orders",
        sa.Column("client_order_id", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=10), nullable=False),
        sa.Column("venue", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("quantity", invertio.persistence.types.DecimalString(length=40), nullable=False),
        sa.Column(
            "limit_price", invertio.persistence.types.DecimalString(length=40), nullable=True
        ),
        sa.Column("post_only", sa.Boolean(), nullable=False),
        sa.Column("stop_loss", invertio.persistence.types.DecimalString(length=40), nullable=True),
        sa.Column(
            "take_profit", invertio.persistence.types.DecimalString(length=40), nullable=True
        ),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("signal_id", sa.String(length=32), nullable=True),
        sa.Column("venue_order_id", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "filled_quantity", invertio.persistence.types.DecimalString(length=40), nullable=False
        ),
        sa.Column(
            "avg_fill_price", invertio.persistence.types.DecimalString(length=40), nullable=True
        ),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column("created_at", invertio.persistence.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", invertio.persistence.types.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
        ),
        sa.PrimaryKeyConstraint("client_order_id"),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index("ix_orders_mode_created", ["mode", "created_at"], unique=False)
        batch_op.create_index("ix_orders_status", ["status"], unique=False)

    op.create_table(
        "fills",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("client_order_id", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=10), nullable=False),
        sa.Column("venue", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("quantity", invertio.persistence.types.DecimalString(length=40), nullable=False),
        sa.Column("price", invertio.persistence.types.DecimalString(length=40), nullable=False),
        sa.Column("fee", invertio.persistence.types.DecimalString(length=40), nullable=False),
        sa.Column("fee_currency", sa.String(length=10), nullable=False),
        sa.Column("ts", invertio.persistence.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_order_id"],
            ["orders.client_order_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fills", schema=None) as batch_op:
        batch_op.create_index("ix_fills_mode_ts", ["mode", "ts"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fills", schema=None) as batch_op:
        batch_op.drop_index("ix_fills_mode_ts")

    op.drop_table("fills")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index("ix_orders_status")
        batch_op.drop_index("ix_orders_mode_created")

    op.drop_table("orders")
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.drop_index("ix_signals_mode_ts")

    op.drop_table("signals")
    with op.batch_alter_table("equity_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_equity_mode_venue_ts")

    op.drop_table("equity_snapshots")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_mode_ts")

    op.drop_table("audit_log")
    # ### end Alembic commands ###
